Issue #26 Updated retry count and handle error message properly

diff --git a/minishift-ci-index.yaml b/minishift-ci-index.yaml
--- a/minishift-ci-index.yaml
+++ b/minishift-ci-index.yaml
@@ -63,19 +63,25 @@
             # testing out the cico client
             set +e
             export CICO_API_KEY=$(cat ~/duffy.key)
-            read CICO_hostname CICO_ssid <<< $(cico node get -f value -c ip_address -c comment --retry-count 6)
-            sshopts="-t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l root"
-            ssh_cmd="ssh $sshopts $CICO_hostname"
-            env > jenkins-env
-            $ssh_cmd yum -y install rsync
-            rsync -e "ssh $sshopts" -Ha $(pwd)/ $CICO_hostname:payload
-            $ssh_cmd -t "cd payload && {ci_cmd}"
-            rtn_code=$?
-            cico node done $CICO_ssid
-            if [[ $rtn_code -eq 124 ]]; then
-              echo "BUILD TIMEOUT";
+            read CICO_hostname CICO_ssid <<< $(cico node get -f value -c ip_address -c comment --retry-count 12)
+
+            if [[ $CICO_hostname != "" ]]; then
+              sshopts="-t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l root"
+              ssh_cmd="ssh $sshopts $CICO_hostname"
+              env > jenkins-env
+              $ssh_cmd yum -y install rsync
+              rsync -e "ssh $sshopts" -Ha $(pwd)/ $CICO_hostname:payload
+              $ssh_cmd -t "cd payload && {ci_cmd}"
+              rtn_code=$?
+              cico node done $CICO_ssid
+              if [[ $rtn_code -eq 124 ]]; then
+                echo "BUILD TIMEOUT";
+              fi
+              exit $rtn_code
+            else
+              echo "CICO: Unable to get Node.";
+              exit 1
             fi
-            exit $rtn_code
 
 - job-template:
     name: '{git_repo}-pr'
@@ -96,20 +102,26 @@
               # testing out the cico client
               set +e
               export CICO_API_KEY=$(cat ~/duffy.key)
-              read CICO_hostname CICO_ssid <<< $(cico node get -f value -c ip_address -c comment --retry-count 6)
-              sshopts="-t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l root"
-              ssh_cmd="ssh $sshopts $CICO_hostname"
-              env > jenkins-env
-              $ssh_cmd yum -y install rsync
-              git rebase origin/${{ghprbTargetBranch}} \
-              && rsync -e "ssh $sshopts" -Ha $(pwd)/ $CICO_hostname:payload \
-              && /usr/bin/timeout {timeout} $ssh_cmd -t "cd payload && {ci_cmd}"
-              rtn_code=$?
-              cico node done $CICO_ssid
-              if [[ $rtn_code -eq 124 ]]; then
-                 echo "BUILD TIMEOUT";
+              read CICO_hostname CICO_ssid <<< $(cico node get -f value -c ip_address -c comment --retry-count 12)
+
+              if [[ $CICO_hostname != "" ]]; then
+                sshopts="-t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l root"
+                ssh_cmd="ssh $sshopts $CICO_hostname"
+                env > jenkins-env
+                $ssh_cmd yum -y install rsync
+                git rebase origin/${{ghprbTargetBranch}} \
+                && rsync -e "ssh $sshopts" -Ha $(pwd)/ $CICO_hostname:payload \
+                && /usr/bin/timeout {timeout} $ssh_cmd -t "cd payload && {ci_cmd}"
+                rtn_code=$?
+                cico node done $CICO_ssid
+                if [[ $rtn_code -eq 124 ]]; then
+                   echo "BUILD TIMEOUT";
+                fi
+                exit $rtn_code
+              else
+                echo "CICO: Unable to get Node.";
+                exit 1
               fi
-              exit $rtn_code
 
 - job-template:
     name: '{git_repo}-docs'
@@ -132,19 +144,25 @@
               # testing out the cico client
               set +e
               export CICO_API_KEY=$(cat ~/duffy.key)
-              read CICO_hostname CICO_ssid <<< $(cico node get -f value -c ip_address -c comment --retry-count 6)
-              sshopts="-t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l root"
-              ssh_cmd="ssh $sshopts $CICO_hostname"
-              env > jenkins-env
-              $ssh_cmd yum -y install rsync
-              rsync -e "ssh $sshopts" -Ha $(pwd)/ $CICO_hostname:payload \
-              && /usr/bin/timeout {timeout} $ssh_cmd -t "cd payload && {ci_cmd}"
-              rtn_code=$?
-              if [[ $rtn_code -eq 124 ]]; then
-                 echo "BUILD TIMEOUT";
+              read CICO_hostname CICO_ssid <<< $(cico node get -f value -c ip_address -c comment --retry-count 12)
+
+              if [[ $CICO_hostname != "" ]]; then
+                sshopts="-t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l root"
+                ssh_cmd="ssh $sshopts $CICO_hostname"
+                env > jenkins-env
+                $ssh_cmd yum -y install rsync
+                rsync -e "ssh $sshopts" -Ha $(pwd)/ $CICO_hostname:payload \
+                && /usr/bin/timeout {timeout} $ssh_cmd -t "cd payload && {ci_cmd}"
+                rtn_code=$?
+                if [[ $rtn_code -eq 124 ]]; then
+                   echo "BUILD TIMEOUT";
+                fi
+                cico node done $CICO_ssid
+                exit $rtn_code
+              else
+                echo "CICO: Unable to get Node.";
+                exit 1
               fi
-              cico node done $CICO_ssid
-              exit $rtn_code
 
 - project:
     name: minishift
